# These are Cloud Build steps. You can read more about cloud build here: 
# https://cloud.google.com/cloud-build/docs/
# All these steps sharing a filesystem between each other.
timeout: 7200s
steps:
  # Executing the notebook
- name: 'us-west2-docker.pkg.dev/public-gcr/ai-workbench/workbench-cli'
  id: 'run-clean-notebook'
  args: ['execute-notebook', '--notebook','./notebooks/clean.ipynb', '--gcs-folder', 'gs://gtc-conf-examples/', '--location', 'us-central1', '--project', 'ml-lab-152505', '--execution-id', '${COMMIT_SHA}', '--wait']
