# These are Cloud Build steps. You can read more about cloud build here: 
# https://cloud.google.com/cloud-build/docs/
# All these steps sharing a filesystem between each other.
timeout: 7200s
steps:
  # We will start with uploading Notebook to the GCS bucker where it can be later on executed by Vertex AI Workbench
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'copy-notebook-to-gcs'
  args: ['cp', './notebooks/clean.ipynb', 'gs://gtc-conf-examples/clean-${COMMIT_SHA}.ipynb']
  dir: 'notebooks-ci-showcase'
