# These are Cloud Build steps. You can read more about cloud build here: 
# https://cloud.google.com/cloud-build/docs/
# All these steps sharing a filesystem between each other.
timeout: 7200s
steps:
  # First, we need to clone the repository that we need to test.
  # This will also clone submodules that are used as dependancies.
- name: 'gcr.io/cloud-builders/git'
  id: 'clone'
  args: ['clone', '--recurse-submodules', '--branch', 'repro_nb_based_pipeline', 'https://github.com/gclouduniverse/notebooks-ci-showcase']
  # Next, we need to checkout the exact commit that we need to test. Otherwise, Cloud Build will be testing the master.
  # Variable $COMMIT_SHA provided by the Cloud Build. You can find more about Cloud Build variables here:
  # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
- name: 'gcr.io/cloud-builders/git'
  id: 'checkout'
  args: ['checkout', '$COMMIT_SHA']
  dir: 'notebooks-ci-showcase'
- name: 'docker.io/library/python:3.7'
  id: 'train'
  args: ['bash', '-c', 'pip install gcloud-notebook-training && git show --name-only $COMMIT_SHA | grep -i .ipynb | xargs -I {} gcloud-notebook-training --input-notebook {}']
  dir: 'notebooks-ci-showcase'
  timeout: 7200s
