# These are Cloud Build steps. You can read more about cloud build here: 
# https://cloud.google.com/cloud-build/docs/
# All these steps sharing a filesystem between each other.
steps:
  # First, we need to clone the repository that we need to test.
  # This will also clone submodules that are used as dependancies.
- name: 'gcr.io/cloud-builders/git'
  id: 'clone'
  args: ['clone', '--recurse-submodules', '--branch', 'container_based_version', 'https://github.com/b0noI/notebooks-ci-showcase']
  # Next, we need to checkout the exact commit that we need to test. Otherwise, Cloud Build will be testing the master.
  # Variable $COMMIT_SHA provided by the Cloud Build. You can find more about Cloud Build variables here:
  # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
- name: 'gcr.io/cloud-builders/git'
  id: 'checkout'
  args: ['checkout', '$COMMIT_SHA']
  dir: 'notebooks-ci-showcase'
- name: 'gcr.io/deeplearning-platform-release/base-cpu:m39'
  id: 'get-container-id'
  args: ['./SelfContainedJupyterNotebooks/utils/get_docker_tag.py', '--path', 'demo.ipynb', '--out-path', './container_uri', '--test']
  dir: 'notebooks-ci-showcase'
  entrypoint: 'python'
- name: 'gcr.io/deeplearning-platform-release/base-cpu:m39'
  id: 'clean'
  dir: 'notebooks-ci-showcase'
  args: [notebooks/clean.ipynb]
  entrypoint: './run_test.sh'
- name: 'gcr.io/deeplearning-platform-release/base-cpu:m39'
  id: 'train'
  dir: 'notebooks-ci-showcase'
  args: [notebooks/train.ipynb]
  entrypoint: './run_test.sh'
- name: 'gcr.io/deeplearning-platform-release/base-cpu:m39'
  id: 'deploy'
  dir: 'notebooks-ci-showcase'
  args: ['--version']
  entrypoint: 'gcloud'
timeout: 1200s
