# These are Cloud Build steps. You can read more about cloud build here: 
# https://cloud.google.com/cloud-build/docs/
# All these steps sharing a filesystem between each other.
timeout: 7200s
steps:
  # Creating unique name for the notebook, just in case to save execution per each commit
- name: 'alpine:3.15'
  id: 'copy-notebook-with-right-name'
  args: ['cp', './notebooks/clean.ipynb', './notebooks/clean-${COMMIT_SHA}.ipynb']
  # Executing the notebook
- name: 'us-west2-docker.pkg.dev/public-gcr/ai-workbench/workbench-cli'
  id: 'run-clean-notebook'
  args: ['execute-notebook', '--notebook','./notebooks/clean-${COMMIT_SHA}.ipynb', '--gcs-folder', 'gs://gtc-conf-examples/', '--location', 'us-central1', '--project', 'ml-lab-152505']
